---
title: "Accessibility"
lang: "en"
output:
  html_document:
    css: www/style.css
---
Last updated: <b>15 March 2021</b>

This website is run by the Scottish Government.

We want it to be accessible and usable for as many people as possible.

## Feedback

[Contact us](https://scotland.shinyapps.io/population_programme/#Contact) if you:

* Cannot access any part of this site or want to report an accessibility problem.  
* Need information on this website in a different format. Such as accessible PDF, large print, easy read, audio recording or braille. We’ll consider your request and get back to you as soon as we can.  

### Enforcement

If you’re not happy with how we respond to your feedback, contact the <a href = 'https://www.equalityadvisoryservice.com/'><u>Equality Advisory and Support Service</u></a>.
They are an independent advice service. They will advise you on what to do next.

## Compliance

Scottish Government is committed to making its websites accessible, in accordance with the Public Sector Bodies (Websites and Mobile Applications) (No. 2) 
<a href = 'http://www.legislation.gov.uk/uksi/2018/952/regulation/4/made'><u>Accessibility Regulations 2018</u></a>.  

This accessibility statement applies to the 
<a href = 'https://scotland.shinyapps.io/population_programme_dashboard/'><u>Population Programme</u></a> data website.

### Compliance status

This website is partially compliant with the regulations, due to the non-compliances listed below.

### Non-accessible content

The content listed below is not-compliant with the regulations:

* The small charts in the Home page table are not accessible for screen readers.
* Some text and shading does not appear in high contrast mode - mostly tooltips within the table.

### Preparation of statement

This statement was prepared on <b>15 March 2021</b>.

These web pages were reviewed <b>February 2021</b>.
